### ISSUE TITLE
GeoPlotter package update error

### ISSUE THREAD

**Issue by sarahsdonohoe** [NOAA-PMEL/EcoFOCI_PopUp#11]
No handles with labels found to put in legend.
C:\Users\donohoe\AppData\Local\Continuum\anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py:388: MatplotlibDeprecationWarning: 
The 'inframe' parameter of draw() was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use Axes.redraw_in_frame() instead. If any parameter follows 'inframe', they should be passed as keyword, not positionally.
  inframe=inframe)

**Comment by shaunwbell** [comment]
This is a cartopy warning - it should not impact the successful processing of popup data at the moment.  future versions of the software may need to address this as libraries get updated (but it will likely be addressed on the cartopy api side and not the local popup code unless a workaround is required to maintain a certain look and feel or backward compatability)
