### ISSUE TITLE
Add Flag or Switch to determine if image code needs to run or not

### ISSUE THREAD

**Issue by shaunwbell** [NOAA-PMEL/EcoFOCI_PopUp#7]
not all popups have camera's and when a popup doesn't have a camera... a large 4gb mythical file gets created (so try to prevent this)

**Comment by sarahsdonohoe** [comment]
we didn't prevent the file from getting created, but as a workaround we added a line that will delete the placeholder image file if it's created

**Comment by sarahsdonohoe** [comment]
we didn't prevent the file from getting created, but as a workaround we added a line that will delete the placeholder image file if it's created
