### ISSUE TITLE
Keep working-overhaul branch separate from main branch for now

### ISSUE THREAD

**Issue by sarahsdonohoe** [NOAA-PMEL/EcoFOCI_PopUp#8]
Everything currently in the main branch is under "archive" in the working-overhaul branch. However, all the information in main is re-organized into different folders broken down by deployment year. Engineering folder in working-overhaul reflects only the most recent builds (Generation 3.2), and archives of engineering folders should be kept for Generations 1, 2 and 3 in the archive folder.  Generations 3, 3.1 and 3.2 are nearly identical in programming. The largest difference is frame design and the circuit board regulator modification.

**Comment by shaunwbell** [comment]
RENAMED overhaul to master and archived older master as another archive.  everyone will want to re download their versions
